# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jOe/n41refmh7+r6oS1+tGJvcdpxTUTZNhgEZM0l7sZpfsJtNBmxrvFdUQyWVnbLKGH2EtTayR8V+LeqnKxbluo231DKNLzyCPxoPp4I2fV7Gc83BdNUyVoTxNUcBRcRNXy1AVkSt6VUKObYOEUjBPFAf1YJF+h57Bk4msh6eqVk6zy4AGhEAdMQSxk233PnT77H5UE5t7ZXaCxkVrK0XnrO6Jn048cGxRsJyHST47mqLhGos1GFoTZVGjnMxWf16SVom0/JUvpabsMgzHZRQzbmmk0Rj+Zdard1XxhRE7SyY2XZUufIjMT/cWFmJZfciXMx7l+xrBc2UDaXBGDXlo6ycCmpi2ply2aKGKf+d7T2u9G8okpSQ+TEyI6Gl7y1PBlQmFT4oTQlo34vLIVrvBpgXu3wHedlfjdn0u8znWo4swF3uUfnxqzo90S0c/42ZBZ6yXFn6azWw4b6GvjUGdWJnez01VvrfQ4DBWjoBy3RiNSycxmxnpStlu+lxvo97aOHTL+1BEQM7gr8+gtbqR/xoB7B2GTZ1MvykAaNO4IteLaAU26uPciG/mXhCt0XVzRUd48DOI7YNSzQHt/MORNbcf+nChypWgMvBb6JmooXRoxUKFBzlpKs2NsTA3v2yjeEGmRPmFe97hFgxJeNoSH/OVQYGQxFgX6r1vI/91g="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
