travis:
  secure:
    BINSTAR_TOKEN: g9Ae9xg4Fx1zgWXVnMN6xHq4D5pv7OvjROuwIBeL9BTMB2e4iJ2OOpQZu2AL1ET6zxwWmQhH6Ssz+h6SQKQgYSL83hCD2qSQO9HwOlonichJwrZMTw3Lkua7bYz9yroclG+kjPiu9TIav2ObiTKxet7yl7DtbMoGmhw0UFqOsME+NbvH+OWDZDEM7EBUNbtGWA0DKxSRfAGF97at11j+cxBzohHhudtbMEGIHobcSXNbg/KuADY+deziQcSDAxOvHpK5vb68y6s9OJR1wohqHP56tP9dFxwIwIskpAeOO1LVW2mFsp6Olp3Ew1UzebSlgMZqwMYY7ybKz7rJMir4EUOYECkNtdkJU72V+aZ6nE+yZRki9OoKIvOyTD3YLzthsD8xF0HFuAb+wwyeoFhtr4J6fRAivFHkf1Zz7xvUs0ANLbkbN1LLRSPYkWjv0L41lx4WJ7i52RLuQszal5DHRwQgn1HI9qhJRSogLfbdFUc/WJO5gT2sTtowzInUIv3uhx69Hz8mOXCWx1tsyVv+gx4sRivtEq54x69SBoPQvnTFtSFK0Vx1W1oekagWT5mSi8PuwWrsl/8ZzpfWZyGHbh9e1JESg1sv94GXEhrEumTnu8rPCJolq8MxsGD6OWyVv5RRZXvbtlRTCSUcj4c8w8GC2WxzsZNPqxc9YlPeVe4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
