travis:
  secure:
    BINSTAR_TOKEN: lz5Vpi796SUKk9SLH1Yb6lP1BquQn5OuEgcff7uxVDoLZxYolToIzM1aTPdiAvto5F7Fnd6UXRobAS/PynXS1ES+fm+ZxloXCS5aMF4a5dRkzXyn520zftjT9bxuWS0JmhgDCSJVqYvoRmfmLhyN3w8Q01E5oegylKiYQDiJOVR+uaa9k9s44ucteppeiUyldpROmDosY9G8A7Q7oIR3RzT3S55B+Ua5vMCFUd0CQ4kJiJ6bnuKBvmi+T3/CPYFDSuB9i8bRcVnNfGtkxJm1bB51pkiz/5fqm7WgEyoiRQh+byCkzQanctX9Sk5t9YwkYKhYS7b3DzUWSdU9yMbrmV1Dxm5TIJp8kvpaSQ6a89flRWF6XPWCdMW0D43yh6a8+Z0UeBrfqErGNtWyBSooqCMFNFfAb0ayDrM7J9/i3qGx3HfLAeNwurBAX706Mp2BqtaOKUJJ6F9x/VDnHmfi1lBV2JIM0UEcueEABwFPBqXT/DspsInRlvTOBwgkwtgFDPTLMhseDgndlOFs3LsQ5U6S1/9fNyZQ/8Vgi5p3x1BjKbYQB0SLjwf5pg1FB2sc5vtuaFXFP+vLdzsL8tseKOYKZOgfRhLSU90/EP7228I8H2yvCK0ExrHpISrtLd+dJhcMbkoWnKirnVXHM7pm3B1LrMdYN5VV6HHp2it3wi4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
