travis:
  secure:
    BINSTAR_TOKEN: jOe/n41refmh7+r6oS1+tGJvcdpxTUTZNhgEZM0l7sZpfsJtNBmxrvFdUQyWVnbLKGH2EtTayR8V+LeqnKxbluo231DKNLzyCPxoPp4I2fV7Gc83BdNUyVoTxNUcBRcRNXy1AVkSt6VUKObYOEUjBPFAf1YJF+h57Bk4msh6eqVk6zy4AGhEAdMQSxk233PnT77H5UE5t7ZXaCxkVrK0XnrO6Jn048cGxRsJyHST47mqLhGos1GFoTZVGjnMxWf16SVom0/JUvpabsMgzHZRQzbmmk0Rj+Zdard1XxhRE7SyY2XZUufIjMT/cWFmJZfciXMx7l+xrBc2UDaXBGDXlo6ycCmpi2ply2aKGKf+d7T2u9G8okpSQ+TEyI6Gl7y1PBlQmFT4oTQlo34vLIVrvBpgXu3wHedlfjdn0u8znWo4swF3uUfnxqzo90S0c/42ZBZ6yXFn6azWw4b6GvjUGdWJnez01VvrfQ4DBWjoBy3RiNSycxmxnpStlu+lxvo97aOHTL+1BEQM7gr8+gtbqR/xoB7B2GTZ1MvykAaNO4IteLaAU26uPciG/mXhCt0XVzRUd48DOI7YNSzQHt/MORNbcf+nChypWgMvBb6JmooXRoxUKFBzlpKs2NsTA3v2yjeEGmRPmFe97hFgxJeNoSH/OVQYGQxFgX6r1vI/91g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
